framework:
    notifier:
        #chatter_transports:
        #    slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        texter_transports:
            
            freemobile: '%env(FREE_MOBILE_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['freemobile']
            high: ['freemobile']
            medium: ['freemobile']
            low: ['freemobile']
        admin_recipients:
            - { email: admin@example.com }
